name: anonymous_bamboo_forest
description: A new Flutter project for Anonymous Bamboo Forest.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  http: ^1.2.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  timeago: ^3.6.1
  shared_preferences: ^2.2.2
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
